# Copyright 2023 SLSA Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: "Secure artifact download"
description: "Download an artifact and verify its SHA256"
inputs:
  name:
    description: "Artifact name. (Note: this is a name given to an upload, not the path or filename)."
    required: true
  path:
    description: "The path of the artifact. (Note: should be the same as the `path` argument passed to secure-upload-artifact or actions/upload-artifact GHA)."
    required: true
  sha256:
    description: "SHA256 of the file for verification."
    required: true
  set-executable:
    description: "Set the artifact as executable."
    required: false

runs:
  using: "composite"
  steps:
    - name: Validate the artifact path
      id: validate-path
      shell: bash
      env:
        UNTRUSTED_PATH: "${{ inputs.path }}"
      run: |
        set -euo pipefail

        # Ensure no directory traversal.
        # NOTE: the actions/download-artifact Action only creates files
        # in the workspace directory, but this may change in the future.
        # TODO(#1893): Consolidate directory traversal checks
        resolved_dir=$(readlink -m "$UNTRUSTED_PATH")
        wd=$(readlink -m "${GITHUB_WORKSPACE}")
        if [[ "${wd}" != "" ]] && [[ "${resolved_dir}" != "${wd}"/* ]] && [[ "${resolved_dir}" != "${wd}" ]]; then
          if [[ "${RUNNER_TEMP}" != "" ]] && [[ "${resolved_dir}" != "${RUNNER_TEMP}"/* ]] && [[ "${resolved_dir}" != "${RUNNER_TEMP}" ]]; then
            if [[ "${resolved_dir}" != /tmp/* ]] && [[ "${resolved_dir}" != "/tmp" ]]; then
              echo "Path is not in the workspace or temp directory: $UNTRUSTED_PATH"
              exit 1
            fi
          fi
        fi

        # Check that the name of the path does not clash with the
        # directory where the builder code is stored.
        results=$(
          echo "$UNTRUSTED_PATH" | grep __BUILDER_CHECKOUT_DIR__ || true
        )
        if [[ "$results" != "" ]]; then
          echo "\"$UNTRUSTED_PATH\" contains '__BUILDER_CHECKOUT_DIR__'"
          echo "$results"
          exit 1
        fi

        # Ensure we don't overwrite existing files.
        if [ -e "$UNTRUSTED_PATH" ]; then
          echo "Path $UNTRUSTED_PATH already exists"
          exit 5
        fi

        # path has been validated. Explicitly trust it and set as an output.
        file_path="${UNTRUSTED_PATH}"
        folder_path="$(dirname ${UNTRUSTED_PATH})"
        echo "file_path=${file_path}" >> "${GITHUB_OUTPUT}"
        echo "folder_path=${folder_path}" >> "${GITHUB_OUTPUT}"

    - name: Download the artifact
      uses: actions/download-artifact@c850b930e6ba138125429b7e5c93fc707a7f8427 # v4.1.4
      with:
        name: "${{ inputs.name }}"
        path: "${{ steps.validate-path.outputs.folder_path }}"

    - name: Compute the hash
      id: compute
      uses: slsa-framework/slsa-github-generator/.github/actions/compute-sha256@main
      with:
        path: "${{ steps.validate-path.outputs.file_path }}"

    # Note: this assumes to top-level re-usable workflow
    # has checkout'ed the builder repository using
    # `.github/actions/secure-builder-checkout`.
    - name: Verify the SHA256
      env:
        UNTRUSTED_EXPECTED_HASH: "${{ inputs.sha256 }}"
        UNTRUSTED_COMPUTED_HASH: "${{ steps.compute.outputs.sha256 }}"
        TRUSTED_PATH: "${{ steps.validate-path.outputs.file_path }}"
        SET_EXECUTABLE: "${{ inputs.set-executable }}"
      shell: bash
      run: |
        set -euo pipefail

        if ! [[ -f "$TRUSTED_PATH" ]]; then
          echo "File $TRUSTED_PATH not present"
          exit 5
        fi

        echo "expected hash is $UNTRUSTED_EXPECTED_HASH"
        echo "computed hash is $UNTRUSTED_COMPUTED_HASH"
        if [[ "$UNTRUSTED_COMPUTED_HASH" != "$UNTRUSTED_EXPECTED_HASH" ]]; then
          echo "hashes do not match"
          rm -rf "${TRUSTED_PATH}"
          exit -2
        fi
        echo "hashes match"
        if [[ "$SET_EXECUTABLE" == "true" ]]; then
          echo "Setting $TRUSTED_PATH as executable"
          chmod u+x "$TRUSTED_PATH"
        fi
