name: "secure-checkout"
description: "Checkout and verify a commit sha for a GitHub repo"

inputs:
  repository:
    description: "The repository to check out."
    required: false
    default: ${{ github.repository }}
  ref:
    description: "A fully formed ref (refs/...) or SHA to checkout."
    required: false
    # NOTE: different from actions/checkout which defaults to GITHUB_REF, GITHUB_SHA, or default branch.
    default: ${{ github.sha }}
  token:
    description: "Token used to fetch the repository."
    required: false
    default: ${{ github.token }}
  persist-credentials:
    description: "Whether to configure the token or SSH key with the local git config"
    # NOTE: different from actions/checkout which defaults to true.
    default: false
  fetch-depth:
    description: "Number of commits to fetch. 0 indicates all history for all branches and tags."
    default: 1
  strict:
    description: "Whether to only allow checkouts from repositories that triggered the workflow."
    default: true
runs:
  using: "composite"
  steps:
    - name: Get expected sha
      id: expected
      shell: bash
      env:
        UNTRUSTED_REPO: "${{ inputs.repository }}"
        UNTRUSTED_REF: "${{ inputs.ref }}"
        GH_TOKEN: "${{ inputs.token }}"
      run: |
        set -euo pipefail
        if [[ "${UNTRUSTED_REF}" =~ ^[a-fA-F0-9]{40}$ ]]; then
          # sha
          sha="${UNTRUSTED_REF}"
        elif [[ "${UNTRUSTED_REF}" == refs/* ]]; then
          # tag
          sha=$(gh api --header 'Accept: application/vnd.github.v3+json' --method GET "/repos/${UNTRUSTED_REPO}/git/${UNTRUSTED_REF}" | jq -r '.object.sha')
        else
          echo "Unsupported ref: ${UNTRUSTED_REF}"
          exit 1
        fi
        echo "::set-output name=sha::$sha"

    - name: Checkout the repository
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2
      with:
        fetch-depth: 1
        ref: ${{ inputs.ref }}
        persist-credentials: ${{ inputs.persist-credentials }}
        repository: ${{ inputs.repository }}
        token: ${{ inputs.token }}

    - name: Verify checkout
      shell: bash
      env:
        CONTEXT: "${{ toJSON(github) }}"
        EXPECTED_SHA: "${{ steps.expected.outputs.sha }}"
      run: |
        set -euo pipefail

        git_sha="$(git log -1 --format='%H')"
        if [[ "$git_sha" != "$EXPECTED_SHA" ]]; then
            echo "mismatch git sha \"$git_sha\" != \"$EXPECTED_SHA\""
            echo "GitHub context:"
            echo "$CONTEXT"
            echo
            echo "Last 20 commits:"
            git log -20
            exit 1
        fi
