name: "Verify a checkout's sha"
description: "verify commit sha for a GitHub repo"

runs:
  using: "composite"
  steps:
    - name: Verify commit sha
      shell: bash
      run: |
        set -euo pipefail

        git_sha=$(git log -1 --format='%H')
        if [[ "$git_sha" != "$GITHUB_SHA" ]]; then
            echo "mismatch git sha $git_sha != $GITHUB_SHA"
            echo "logs:"
            git log
            exit 1
        fi
