# Copyright 2023 SLSA Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: "secure-builder-checkout"
description: "Checkout the builder repository"

inputs:
  repository:
    description: "The repository to check out."
    required: true
  ref:
    description: "The ref to checkout."
    required: true
  path:
    # Same argument to https://github.com/actions/checkout.
    description: "Relative path under $GITHUB_WORKSPACE to place the repository."
    required: true
  token:
    description: "Token used to fetch the repository."
    required: false
    default: ${{ github.token }}
runs:
  using: "composite"
  steps:
    # TODO(968): verify the hash is on the main branch
    # and has an associated release. This will require exceptions
    # for e2e tests.
    - name: Checkout the repository
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
        token: ${{ inputs.token }}
        path: ${{ inputs.path }}
        persist-credentials: false
        fetch-depth: 1
