---
run:
  concurrency: 2
  deadline: 5m
issues:
  # TODO(github.com/slsa-framework/slsa-github-generator/issues/450): revive `package-comments` and `exported` rules.
  include:
    - EXC0012
    - EXC0013
    - EXC0014
  # - EXC0015
  # Maximum issues count per one linter.
  # Set to 0 to disable.
  # Default: 50
  max-issues-per-linter: 0
  # Maximum count of issues with the same text.
  # Set to 0 to disable.
  # Default: 3
  max-same-issues: 0
  new-from-rev: ""
linters:
  disable-all: true
  enable:
    # Some linters have been removed because of the go 1.18 issues.
    # https://github.com/golangci/golangci-lint/issues/2649
    - asciicheck
    - deadcode
    - depguard
    - dogsled
    # TODO(github.com/slsa-framework/slsa-github-generator/issues/450): enable errcheck
    # - errcheck
    # TODO(github.com/slsa-framework/slsa-github-generator/issues/450): enable errorlint
    # - errorlint
    - exhaustive
    # TODO(github.com/slsa-framework/slsa-github-generator/issues/450): enable exportloopref
    # - exportloopref
    # TODO(github.com/slsa-framework/slsa-github-generator/issues/450): enable gci
    # - gci
    - gochecknoinits
    - gocognit
    - goconst
    # TODO(github.com/slsa-framework/slsa-github-generator/issues/450): enable gocritic
    # - gocritic
    - gocyclo
    - godot
    # TODO(github.com/slsa-framework/slsa-github-generator/issues/450): enable godox
    # - godox
    # TODO(github.com/slsa-framework/slsa-github-generator/issues/450): enable goerr113
    # - goerr113
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomodguard
    - goprintffuncname
    # TODO(github.com/slsa-framework/slsa-github-generator/issues/450): enable gosec
    # - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - makezero
    - misspell
    - nakedret
    # TODO(github.com/slsa-framework/slsa-github-generator/issues/450): enable nestif
    # - nestif
    - nolintlint
    # TODO(github.com/slsa-framework/slsa-github-generator/issues/450): enable paralleltest
    # - paralleltest
    - predeclared
    - revive
    - staticcheck
    # TODO(github.com/slsa-framework/slsa-github-generator/issues/450): enable stylecheck
    # - stylecheck
    # TODO(github.com/slsa-framework/slsa-github-generator/issues/450): enable thelper
    # - thelper
    - typecheck
    - unconvert
    - unused
    - varcheck
    - whitespace
    # TODO(github.com/slsa-framework/slsa-github-generator/issues/450): enable thelper
    # - wrapcheck
linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    enable:
      - fieldalignment
  godox:
    keywords:
      - BUG
      - FIXME
      - HACK
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/slsa-framework/slsa-github-generator)
  gocritic:
    enabled-checks:
      # Diagnostic
      - appendAssign
      - argOrder
      - badCond
      - caseOrder
      - codegenComment
      - commentedOutCode
      - deprecatedComment
      - dupArg
      - dupBranchBody
      - dupCase
      - dupSubExpr
      - exitAfterDefer
      - flagDeref
      - flagName
      - nilValReturn
      - offBy1
      - sloppyReassign
      - weakCond
      - octalLiteral

      # Performance
      - appendCombine
      - equalFold
      - hugeParam
      - indexAlloc
      - rangeExprCopy
      - rangeValCopy

      # Style
      - assignOp
      - boolExprSimplify
      - captLocal
      - commentFormatting
      - commentedOutImport
      - defaultCaseOrder
      - docStub
      - elseif
      - emptyFallthrough
      - emptyStringTest
      - hexLiteral
      - ifElseChain
      - methodExprCall
      - regexpMust
      - singleCaseSwitch
      - sloppyLen
      - stringXbytes
      - switchTrue
      - typeAssertChain
      - typeSwitchVar
      - underef
      - unlabelStmt
      - unlambda
      - unslice
      - valSwap
      - wrapperFunc
      - yodaStyleExpr

      # Opinionated
      - builtinShadow
      - importShadow
      - initClause
      - nestingReduce
      - paramTypeCombine
      - ptrToRefParam
      - typeUnparen
      - unnecessaryBlock
