# MD004/ul-style - Unordered list style
MD004:
  style: "dash"

# MD007/ul-indent - Unordered list indentation
MD007:
  indent: 2

# MD013/line-length - Line length
MD013: false

# TODO(#): Re-enable duplicate heading checks.
# MD024/no-duplicate-heading - Disable for now.
MD024: false

# MD025/single-title/single-h1 - Multiple top-level headings
MD025:
  # Disable checking of YAML frontmatter.
  front_matter_title: ""

# MD028/no-blanks-blockquote - Blank line inside blockquote
MD028: false

# MD029/ol-prefix - Ordered list item prefix
MD029:
  # List style
  style: "ordered"

# MD030/list-marker-space - Spaces after list markers
MD030:
  # Spaces for single-line unordered list items
  ul_single: 1
  # Spaces for single-line ordered list items
  ol_single: 1
  # Spaces for multi-line unordered list items
  ul_multi: 1
  # Spaces for multi-line ordered list items
  ol_multi: 1

# MD033/no-inline-html - Inline HTML
MD033: false

# MD034/no-bare-urls - Bare URL used
MD034: false

# MD046/code-block-style - Code block style
MD046:
  style: "fenced"

# MD047/single-trailing-newline - Files should end with a single newline character
MD047: true

# MD048/code-fence-style - Code fence style
MD048:
  style: "backtick"

# Disable checks that currently have bugs:
MD051: false # https://github.com/DavidAnson/markdownlint/issues/538
MD053: false # https://github.com/DavidAnson/markdownlint/issues/537
