name: "Generate the builder"
description: "Build or fetch the builder binary"
inputs:
  ref:
    description: "Ref of the builder."
    required: true
  repository:
    description: "Repository of the builder."
    required: true
  binary:
    description: "Name of the compiled binary. (Note: just the filename, not the path)"
    required: true
  compile-builder:
    description: "Whether to compile the builder or not."
    required: true
  directory:
    description: "Directory of the source code of the builder. (Note: expect no trailing `/`)"
    required: true
  go-version:
    description: "The Go version to use, as expected by https://github.com/actions/setup-go."
    required: true

  token:
    description: "GitHub token"
    required: false
    default: ${{ github.token }}

outputs:
  sha256:
    description: "SHA256 of the builder binary."
    value: ${{ steps.compute.outputs.sha256 }}

runs:
  using: "composite"
  steps:
    - name: Checkout the Go builder repository
      # uses: ./.github/actions/checkout-go
      uses: slsa-framework/slsa-github-generator/.github/actions/checkout-go@fe4b511143bc6fb575303b60d4361decbe5a2df3
      with:
        repository: "${{ inputs.repository }}"
        ref: "${{ inputs.ref }}"
        go-version: "${{ inputs.go-version }}"

    - name: Generate builder
      shell: bash
      env:
        COMPILE_BUILDER: "${{ inputs.compile-builder }}"
        BUILDER_REF: "${{ inputs.ref }}"
        BUILDER_DIR: "${{ inputs.directory }}"
        BUILDER_BINARY: "${{ inputs.binary }}"
        # Needed for the gh CLI used in builder-fetch.sh.
        GH_TOKEN: "${{ inputs.token }}"
      run: ./.github/actions/generate-builder/generate-builder.sh

    - name: Compute sha256 of builder
      # uses: ./.github/actions/compute-sha256
      uses: slsa-framework/slsa-github-generator/.github/actions/compute-sha256@fe4b511143bc6fb575303b60d4361decbe5a2df3
      id: compute
      with:
        path: "${{ inputs.binary }}"
