name: "Checkout a repository for a Node project"
description: "Checkout and setup the environment for a Node project"
inputs:
  path:
    # Same argument to https://github.com/actions/checkout.
    description: "Relative path under $GITHUB_WORKSPACE to place the repository."
    required: true
  token:
    description: "The token to use."
    required: false
    # Same default as https://github.com/actions/checkout/blob/main/action.yml#L24.
    default: ${{ github.token }}
  node-version:
    description: "The Node version to use, as expected by https://github.com/actions/setup-node."
    required: true

runs:
  using: "composite"
  steps:
    # Note: this assumes to top-level re-usable workflow
    # has checkout'ed the builder repository using
    # `.github/actions/secure-builder-checkout`.
    - name: Checkout the repository with user ref
      uses: ./__BUILDER_CHECKOUT_DIR__/.github/actions/secure-project-checkout
      with:
        token: ${{ inputs.token }}
        path: ${{ inputs.path }}

    - name: Set up Node environment
      uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # tag=v3.4.1
      with:
        node-version: ${{ inputs.node-version }}
