# Copyright 2023 SLSA Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: "secure-project-checkout"
description: "Checkout a project and verify its commit sha"

inputs:
  checkout-sha1:
    description: "The sha1 to checkout."
    required: false
    default: ""

  fetch-depth:
    # Same argument to https://github.com/actions/checkout.
    description: "Number of commits to fetch. 0 indicates all history for all branches and tags."
    required: false
    default: 1
  path:
    # Same argument to https://github.com/actions/checkout.
    description: "Relative path under $GITHUB_WORKSPACE to place the repository."
    required: true
  # The token is not available to actions by defaults, so we need to
  # share it explicitly. The token is needed to checkout private repositories.
  token:
    description: "Token used to fetch the repository."
    required: false
    default: ${{ github.token }}
runs:
  using: "composite"
  steps:
    - name: Checkout the repository
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        ref: ${{ inputs.checkout-sha1 }}
        # Different from default actions/checkout which defaults to `true`.
        persist-credentials: false
        token: ${{ inputs.token }}
        path: ${{ inputs.path }}

    - name: Verify commit sha
      shell: bash
      env:
        CONTEXT: "${{ toJSON(github) }}"
        CHECKOUT_SHA1: "${{ inputs.checkout-sha1 }}"
      working-directory: "${{ inputs.path }}"
      run: |
        set -euo pipefail

        git_sha="$(git log -1 --format='%H')"
        # By default, we clone at the sha indicated by the GitHub event.
        checkout_sha="$GITHUB_SHA"

        # If the user provided a sha, we use it instead.
        if [[ -n "${CHECKOUT_SHA1:-}" ]]; then
          checkout_sha="${CHECKOUT_SHA1}"
        fi

        # Verify that the sha is correctly formatted.
        regex="^[a-fA-F0-9]{40}$"
        if [[ ! "$checkout_sha" =~ $regex ]]; then
            echo "invalid sha: $checkout_sha"
            exit 1
        fi

        # Note: For pull requests, the `$GITHUB_SHA` corresponds to the
        # merge commit that GitHub automatically creates.
        # It is consistent with what the checkout Actions pulls.
        # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows.

        if [[ "$git_sha" != "$checkout_sha" ]]; then
            echo "mismatch git sha \"$git_sha\" != \"$checkout_sha\""
            echo "GitHub context:"
            echo "$CONTEXT"
            echo
            echo "Last 20 commits:"
            git log -20
            exit 1
        fi
