name: "SHA256 of a file"
description: "Compute the SHA256 of a file"
inputs:
  path:
    description: "Path to a file."
    required: true
outputs:
  sha256:
    description: "The SHA256 of the file."
    value: "${{ steps.compute.outputs.sha256 }}"

runs:
  using: "composite"
  steps:
    - name: Compute the sha256
      id: compute
      shell: bash
      env:
        UNTRUSTED_PATH: "${{ inputs.path }}"
      run: |

        set -euo pipefail

        echo "Computing SHA245 for $UNTRUSTED_PATH"

        if [[ ! -f "$UNTRUSTED_PATH" ]]; then
            echo "File $UNTRUSTED_PATH not present"
            exit 5
        fi

        digest=$(sha256sum "$UNTRUSTED_PATH" | awk '{print $1}')

        echo "::set-output name=sha256::$digest"
