name: "Secure folder download"
description: "Download a folder and verify its SHA256"
inputs:
  name:
    description: "Artifact name. (Note: this is a name given to an upload, not the path or filename)."
    required: true
  path:
    description: "The path to download the folder into. (Must be under the GITHUB_WORKSPACE)"
    required: false
    default: "."
  sha256:
    description: "SHA256 of the file for verification."
    required: true

runs:
  using: "composite"
  steps:
    - name: Compute a random value
      id: rng
      uses: slsa-framework/slsa-github-generator/.github/actions/rng@main

    - name: Download the artifact
      uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
      with:
        name: "${{ inputs.name }}"
        path: "${{ steps.rng.outputs.random }}"

    - name: Compute the hash
      id: compute
      uses: slsa-framework/slsa-github-generator/.github/actions/compute-sha256@main
      with:
        path: "${{ steps.rng.outputs.random }}/folder.tgz"

    - name: Verify the SHA256
      env:
        UNTRUSTED_EXPECTED_HASH: "${{ inputs.sha256 }}"
        UNTRUSTED_COMPUTED_HASH: "${{ steps.compute.outputs.sha256 }}"
        TRUSTED_FOLDER: "${{ steps.rng.outputs.random }}/folder.tgz"
      shell: bash
      run: |
        set -euo pipefail

        if ! [[ -f "${TRUSTED_FOLDER}" ]]; then
          echo "File '${TRUSTED_FOLDER}' not present"
          exit 5
        fi

        echo "expected hash is ${UNTRUSTED_EXPECTED_HASH}"
        echo "computed hash is ${UNTRUSTED_COMPUTED_HASH}"
        if [[ "${UNTRUSTED_COMPUTED_HASH}" != "${UNTRUSTED_EXPECTED_HASH}" ]]; then
          echo "hashes do not match"
          exit -2
        fi
        echo "hashes match"

    - name: Extract tarball content
      shell: bash
      env:
        TRUSTED_FOLDER: "${{ steps.rng.outputs.random }}"
        UNTRUSTED_PATH: "${{ inputs.path }}"
      run: |
        set -euo pipefail

        tempdir=$(mktemp -d)
        tar -xzvf "${TRUSTED_FOLDER}/folder.tgz" --directory "${tempdir}"
        rm -rf "${TRUSTED_FOLDER}"

        # Ensure no directory traversal.
        # Remove possible trailing '/'.
        resolved_dir=$(readlink -m "${UNTRUSTED_PATH}")
        wd=$(readlink -m "$PWD")
        if [[ "$resolved_dir" != "$wd"/* ]]; then
          echo "Path is not in the current directory: ${UNTRUSTED_PATH}"
          exit 1
        fi

        # Move all entries (file or folder).
        for file in "${tempdir}"/*; do
            # Ensure we don't overwrite existing files.
            if [ -e "${resolved_dir}/${file}" ]; then
              echo "Path '${resolved_dir}/${file}'' already exists"
              exit 5
            fi
            mv "${file}" "${resolved_dir}/"
        done

