name: "Secure folder upload"
description: "Upload a folder as a tarball and outputs its SHA256"
inputs:
  name:
    description:: >
      Artifact name.
      The caller is responsible to provide a name that is unique and does not collise with other artifacts.
      An example is to use `${RNG}-artifact`.
    required: true
  path:
    description: 'Path to the folder'
    required: true
outputs:
  sha256:
    description: "SHA256 of the uploaded tarball."
    value: "${{ steps.upload.outputs.sha256 }}"

runs:
  using: "composite"
  steps:
    - name: Validate the path and create the tarball
      id: create
      shell: bash
      env:
        UNTRUSTED_PATH: ${{ inputs.path }}
      run: |
        set -euo pipefail

        if [[ ! -d "${UNTRUSTED_PATH}" ]]; then
          echo "'${UNTRUSTED_PATH}' is not a directory"
          exit 1
        fi

        # Ensure no directory traversal.
        resolved_dir=$(readlink -m "${UNTRUSTED_PATH}")
        wd=$(readlink -m "$PWD")
        if [[ "$resolved_dir" != "$wd"/* ]]; then
          echo "Path is not in the current directory: ${UNTRUSTED_PATH}"
          exit 1
        fi

        tempdir=$(mktemp -d)
        tarball_path="${tempdir}/folder.tgz"
        tar -czvf "${tarball_path}" "${UNTRUSTED_PATH}"
        echo "tarball-path=${tarball_path}" >> "$GITHUB_OUTPUT"

    - name: Upload the artifact
      id: upload
      uses: slsa-framework/slsa-github-generator/.github/actions/secure-upload-artifact@main
      with:
        name: "${{ inputs.name }}"
        path: "${{ steps.create.outputs.tarball-path }}"
