name: setup token

description: "Create a SLSA token for the delegated workflow"

inputs:
  slsa-version:
    description: "The version of SLSA provenance format to output."
    required: false
    default: "v1-rc1"

  slsa-workflow-recipient:
    description: >
      The workflow filename that this token is intended for.

      Example: delegator_generic_slsa3.yml
    type: string
    required: true

  slsa-rekor-log-public:
    description: "If true, private repositories can post to the public transparency log."
    required: false
    type: boolean
    default: false

  slsa-build-action-path:
    description: >
      The action path to invoke, from the root of the repository where this action is invoked
      Example: ./actions/build-artifacts'
    type: string
    required: true

  slsa-checkout-sha1:
    description: "The git commit to checkout the repository."
    required: false

  slsa-runner-label:
    description: >
      The runner label to run the callback Action (`slsa-build-action-path`) on.
    type: choice
    options:
      - ubuntu-latest
    required: true

  slsa-checkout-fetch-depth:
    # Same argument to https://github.com/actions/checkout.
    description: "Number of commits to fetch. 0 indicates all history for all branches and tags."
    required: false
    default: 1

  slsa-workflow-inputs:
    description: >
      A JSON object containing the inputs to the Tool Reusable Workflow (TRW).
      The inputs will be recorded in the provenance as the builder's inputs and
      passed to the tool's build Action.

      Note: The TRW is the reusable workflow calling this Action.
    type: string
    required: true

  slsa-workflow-masked-inputs:
    description: >
      A comma-separated list of input fields to mask in the provenance.
      It should be used for fields that have low-entropy values
      but need to be kept private. The masking will replace
      the value of the fields with '***'. Use this option to mask
      usernames, emails or other PII inputs.

      Example: field1, field2, field3
    type: string
    required: false

outputs:
  slsa-token:
    description: "SLSA token"

runs:
  using: "node16"
  main: "dist/index.js"
