name: pre-submit apis

on:
  push:
    branches: [main, "*"]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [main]
  merge_group:
  workflow_dispatch:

permissions:
  contents: read # Needed to check out the repo.

jobs:
  verify-safe-apis:
    name: verify safe APIs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: Check safe file systems APIs
        run: ./.github/workflows/scripts/pre-submit.apis/verify-safefs.sh
