name: pre-submit base images

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions: read-all

jobs:
  verify-base-images:
    name: verify base images
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
      - name: install cosign
        uses: sigstore/cosign-installer@9becc617647dfa20ae7b1151972e9b3a2c338a2b # tag=v2.8.1
      - name: verify images
        run: ./.github/workflows/scripts/verify-base-images.sh
