# Copyright 2023 SLSA Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: pre-submit e2e generic main

on:
  # Daily run.
  schedule:
    - cron: "0 4 * * *"
  pull_request:
    branches: [main]
  merge_group:
  workflow_dispatch:

permissions: read-all

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  BUILD_ARTIFACT: build-artifact

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      hashes: ${{ steps.hash.outputs.hashes }}
    steps:
      - run: echo "gundam" > build-artifact
      - uses: actions/upload-artifact@89ef406dd8d7e03cfd12d9e0a4a378f454709029 # v4.3.5
        with:
          name: ${{ env.BUILD_ARTIFACT }}
          path: ./${{ env.BUILD_ARTIFACT }}
          if-no-files-found: error
      - name: Generate hashes
        shell: bash
        id: hash
        env:
          FILE: ${{ env.BUILD_ARTIFACT }}
        run: |
          echo "hashes=$(sha256sum $FILE | base64 -w0)" >> "$GITHUB_OUTPUT"

  attest:
    needs: [build]
    permissions:
      id-token: write # For signing.
      contents: write # For asset uploads.
      actions: read # For reading workflow info.
    uses: ./.github/workflows/generator_generic_slsa3.yml
    with:
      base64-subjects: ${{ needs.build.outputs.hashes }}
      compile-generator: true
      provenance-name: build.intoto.jsonl

  verify:
    needs: [build, attest]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: ${{ env.BUILD_ARTIFACT }}
      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
      - run: go install github.com/slsa-framework/slsa-verifier/v2/cli/slsa-verifier@main
      - env:
          SLSA_VERIFIER_TESTING: "true"
          ARTIFACT: ./${{ env.BUILD_ARTIFACT }}
          PROVENANCE: ./${{ needs.attest.outputs.provenance-name }}
          SOURCE: github.com/${{ env.GITHUB_REPOSITORY }}
          REF: ${{ env.GITHUB_REF }}
        run: slsa-verifier verify-artifact --provenance-path "$PROVENANCE" \
              --source-uri "$SOURCE" \
              --source-tag "$REF" \
              "$ARTIFACT"
