name: pre-submit e2e generic workflow
on:
  pull_request:
    branches: [main]

env:
  THIS_FILE: pre-submit.e2e.generic.workflow.yml

jobs:
  build:
    permissions:
      id-token: write # For signing.
      contents: write # For asset uploads.
      actions: read # For reading workflow info.
    uses: ./.github/workflows/slsa2_provenance.yml
    with:
      subjects: "2e0390eb024a52963db7b95e84a9c2b12c004054a7bad9a97ec0c7c89d4681d2    binary-name"

  verify:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 #v2.4.0
      - uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741
        with:
          name: ${{ needs.build.outputs.attestation-name }}
      - env:
          PROVENANCE: ${{ needs.build.outputs.attestation-name }}
        run: |
          set -euo pipefail

          source "./.github/workflows/scripts/e2e-utils.sh"

          echo $PROVENANCE
          pwd
          ls -lh .
          echo "--"
          cat "$PROVENANCE"
          echo "--"

          # disable pipefail and use cat in order to swallow base64 errors.
          set +o pipefail
          cat "$PROVENANCE" | base64 -d | cat
          ATTESTATION=$(cat "$PROVENANCE" | base64 -d | cat)
          set -o pipefail

          echo "--"
          echo $ATTESTATION | jq

          e2e_verify_predicate_subject_name "$ATTESTATION" "binary-name"
          e2e_verify_predicate_builder_id "$ATTESTATION" "https://github.com/Attestations/GitHubHostedActions@v1"
          e2e_verify_predicate_builderType "$ATTESTATION" "https://github.com/slsa-framework/slsa-github-generator@v1"

          # e2e_verify_predicate_invocation_configSource "$ATTESTATION" "{\"uri\":\"git+https://github.com/$GITHUB_REPOSITORY@$GITHUB_REF\",\"digest\":{\"sha1\":\"$GITHUB_SHA\"},\"entryPoint\":\"$GITHUB_WORKFLOW\"}"

          e2e_verify_predicate_invocation_environment "$ATTESTATION" "github_actor" "$GITHUB_ACTOR"
          e2e_verify_predicate_invocation_environment "$ATTESTATION" "github_sha1" "$GITHUB_SHA"
          e2e_verify_predicate_invocation_environment "$ATTESTATION" "os" "ubuntu20"
          e2e_verify_predicate_invocation_environment "$ATTESTATION" "arch" "X64"
          e2e_verify_predicate_invocation_environment "$ATTESTATION" "github_event_name" "$GITHUB_EVENT_NAME"
          e2e_verify_predicate_invocation_environment "$ATTESTATION" "github_ref" "$GITHUB_REF"
          e2e_verify_predicate_invocation_environment "$ATTESTATION" "github_ref_type" "$GITHUB_REF_TYPE"

          # TODO: more tests.
