# Copyright The GOSST team.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: SLSA provenance generator

permissions:
  contents: read

env:
  # This repo.
  GENERATOR_REPOSITORY: ianlewis/slsa-github-generator
  GENERATOR_REF: slsa-gen-lib-ianlewis

###################################################################
#                                                                 #
#            Input and output argument definitions                #
#                                                                 #
###################################################################
on:
  workflow_call:
    inputs:
      artifacts:
        description: "A comma delimited list of artifacts of the form NAME@SHA256"
        required: true
        type: string
    outputs:
      attestation-name:
        description: "The artifact name of the signed provenance"
        value: ${{ jobs.sign-prov.outputs.prov-name }}

jobs:
  ###################################################################
  #                                                                 #
  #                       Build the generator                       #
  #                                                                 #
  ###################################################################
  generator:
    outputs:
      go-generator-sha256: ${{ steps.generator-gen.outputs.go-generator-sha256 }}
      go-prov-sha256: ${{ steps.generator-gen.outputs.go-prov-sha256 }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.3.4
        with:
          fetch-depth: 0
          repository: "${{ env.GENERATOR_REPOSITORY }}"
          ref: "${{ env.GENERATOR_REF }}"

      - name: Set up golang environment
        uses: actions/setup-go@424fc82d43fa5a37540bae62709ddcc23d9520d4 # v2.1.3
        with:
          go-version: 1.18

      - name: Download dependencies
        shell: bash
        run: |
          set -euo pipefail
          #TODO(reproducible)
          go mod vendor

      # TODO(hermeticity) OS-level.

      - name: Build slsa-github-generator
        shell: bash
        id: generator-gen
        run: |
          set -euo pipefail

          # https://go.dev/ref/mod#build-commands.
          go build -mod=vendor -o slsa-github-generator github.com/slsa-framework/slsa-github-generator/cmd/slsa-github-generator
          GENERATOR_DIGEST=$(sha256sum slsa-github-generator | awk '{print $1}')
          echo "::set-output name=go-generator-sha256::$GENERATOR_DIGEST"
          echo "hash of slsa-github-generator is $GENERATOR_DIGEST"

      - name: Upload slsa-github-generator
        uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2.3.1
        with:
          name: "slsa-github-generator"
          path: "slsa-github-generator"
          if-no-files-found: error
          retention-days: 5

  ###################################################################
  #                                                                 #
  #                 Generate the SLSA provenance                    #
  #                                                                 #
  ###################################################################
  provenance:
    runs-on: ubuntu-latest
    needs: [generator]
    permissions:
      id-token: write # Needed for keyless.
      contents: read
    steps:
      - name: Download generator
        uses: actions/download-artifact@f023be2c48cc18debc3bacd34cb396e0295e2869 # v2.1.0
        with:
          name: "slsa-github-generator"

      - name: Verify slsa-github-generator
        env:
          GENERATOR_HASH: "${{ needs.generator.outputs.go-generator-sha256 }}"
        run: |
          set -euo pipefail

          echo "hash of slsa-github-generator should be $GENERATOR_HASH"
          COMPUTED_HASH=$(sha256sum slsa-github-generator | awk '{print $1}')
          echo "slsa-github-generator hash computed is $COMPUTED_HASH"

          # Compare hashes. Explicit exit to be safe.
          # TODO: remove the generator as well.
          echo "$GENERATOR_HASH slsa-github-generator" | sha256sum --strict --check --status || exit -2

          # Make the binary executable.
          chmod a+x slsa-github-generator

      - name: Create and sign provenance
        id: sign-prov
        shell: bash
        env:
          SUBJECTS: "${{ inputs.artifacts }}"
          GITHUB_CONTEXT: "${{ toJSON(github) }}"
        run: |
          set -euo pipefail

          echo "provenance generator is slsa-github-generator"

          # Create and sign provenance
          # This sets signed-provenance-name to the name of the signed DSSE envelope.
          ./slsa-github-generator attest --subjects "${SUBJECTS}" -g attestation.intoto.jsonl

          echo "::set-output name=signed-provenance-name::attestation.intoto.jsonl"

      - name: Upload the signed provenance
        uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2.3.1
        with:
          name: "${{ steps.sign-prov.outputs.signed-provenance-name }}"
          path: "${{ steps.sign-prov.outputs.signed-provenance-name }}"
          if-no-files-found: error
          retention-days: 5
