name: detect env
on:
  workflow_dispatch:

permissions: read-all

jobs:
  #foo
  detect:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      actions: read
      actions: write
    steps:
      # - uses: actions/checkout@v3
      #   with:
      #     repository: slsa-framework/slsa-github-generator
      #     ref: 8d0cdc6af66f20f62b5a58df634077cb421b68fd
      - id: detectenv
        # uses: slsa-framework/slsa-github-generator/.github/actions/detect-workflow@8d0cdc6af66f20f62b5a58df634077cb421b68fd
        uses: slsa-framework/slsa-github-generator/.github/actions/detect-workflow@aec5cd1e20507a6f1b5d8e82a8f62c3e2ca9b9f9
      - id: print
        shell: bash
        env:
          REPO: "${{ steps.detectenv.outputs.repository }}"
          REF: "${{ steps.detectenv.outputs.ref }}"
        run: |
          echo $REPO
          echo $REF
